version: 2
jobs:
  build:
    docker:
      - image: docker:18.09.1
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - run: |
        TAG=0.1.$CIRCLE_BUILD_NUM
        docker build -t vsbmeza/sam:$TAG .
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push vsbmeza/sam:$TAG